# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-22 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0016_ontologysource_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accession',
            old_name='cs_number',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='accession',
            old_name='collector',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='accession',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='accession',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='accession',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='accession',
            name='sitename',
        ),
        migrations.AddField(
            model_name='accession',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='population',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
